import StyledComponentsRegistry from '@/layer-app/AntdRegistry'
import '@/layer-app/styles/globals.css'
import type { Metadata, } from 'next'
import { Inter as interFont, } from 'next/font/google'

const inter = interFont({ subsets: [ 'latin', 'cyrillic', ], weight: [ '100', '400' ] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <StyledComponentsRegistry>
          { children }
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
