import StyledComponentsRegistry from '@/layer-app/AntdRegistry'
import '@/layer-app/styles/globals.css'
import type { Metadata, } from 'next'
import { Inter as interFont, } from 'next/font/google'

import { Providers, } from '@/shared/model/store/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <Providers>
          <StyledComponentsRegistry>
            { children }
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  )
}
